window.l_loc =  {
    'l_pl1' : 'Wpisz numer telefonu',
    'l_pl2' : 'Wpisz imię i nazwisko',
    'l_pl3' : 'Niepoprawne imię i nazwisko',
    'l_pl4' : 'Wprowadzony numer telefonu jest za krótki',
    'l_pl5' : 'Wprowadzony numer telefonu jest za długi',
    'l_pl6' : 'Niestety, podczas składania zamówienia pojawił się błąd. Prosimy zadzwonić na nasza infolinię: +48123456789',
    'l_pl7' : 'Szanowny kliencie, utworzyłeś zamówienie dwukrotnie. Jeśli chcesz skorygować pierwsze zamówienie, zaczekaj na telefon od menedżera ds. logistyki, aby wprowadzić potrzebne zmiany.',
    'l_pl8' : 'Przepraszamy, dostawa do Twojego kraju nie jest możliwa',
    'l_pl9' : 'Dziękujemy za zamówienie. Nasz menedżer wkrótce skontaktuje się z Tobą!',
    'l_pl10' : 'Potwierdź poprawność numeru:',
    'l_pl11' : 'TAK',
    'l_pl12' : 'NIE',
    'l_pl13' : 'Uwaga, promocja!',
    'l_pl14' : 'Specjalnie dla Ciebie i tylko teraz przygotowaliśmy szaloną <strong>zniżkę!</strong>',
    'l_pl15' : 'Specjalnie dla Ciebie i tylko teraz przygotowaliśmy szaloną <strong><span class="green-text">zniżkę!</span></strong>',
    'l_pl16' : 'Złóż zamówienie już teraz i skorzystaj z naszej promocji.',
    'l_pl17' : 'ofert promocyjnych',
    'l_pl18' : 'osób przegląda tę stronę',
    'l_pl19' : 'Uwaga! To już ostatnia oferta promocyjna.',
    'l_pl20' : 'Telefon:',
    'l_pl21' : 'Na przykład: +48412345678',
    'l_pl22' : 'Obecna cena:',
    'l_pl23' : 'Obecna <br/> cena:',
    'l_pl24' : 'Zamów i oszczędź {{discount_price}} {{currency}}',
    'l_pl25' : 'CHWILECZKĘ!',
    'l_pl26' : 'Zanim nas opuścisz, mamy dla Ciebie PREZENT!',
    'l_pl27' : 'Możemy obniżyć cenę do {{unload_price}} {{currency}}!',
    'l_pl28' : 'Aby otrzymać zniżkę, kliknij przycisk „Zostań” na tej stronie',
    'l_pl29' : 'Zanim nas opuścisz, zapoznaj się z naszą ofertą!',
    'l_pl30' : 'Możemy zaoferować Ci produkt w oparciu o BARDZO korzystne warunki!',
    'l_pl31' : 'Aby zobaczyć ofertę, kliknij przycisk „Zostań’ na tej stronie',
    'l_pl32' : 'Zamów połączenie zwrotne',
    'l_pl33' : 'Zadzwonimy do Ciebie w ciągu 1 minuty!',
    'l_pl34' : 'Wszystkie połączenia są <strong>bezpłatne!</strong>',
    'l_pl35' : '<strong>Uwaga!</strong> Aby otrzymać zniżkę, przedstaw menedżerowi kod promocyjny: <b style="margin-top: 15px;font-size: 20px;" class="prefix_value"></b>',
    'l_pl36' : 'Polityka prywatności',
    'l_pl37' : 'Regulamin użytkowania',
    'l_pl38' : 'Czekam na telefon',
    'l_pl39' : 'Nie chcesz czekać?',
    'l_pl40' : 'Pozostało',
    'l_pl41' : 'ofert promocyjnych',
    'l_pl42' : 'ofert promocyjnych',
    'l_pl43' : ' ',
    'l_pl44' : 'Nieprawidłowe pole „E-mail”',
    'l_pl45' : 'Numer telefonu',
    'l_pl46' : 'Odmówić',
    'l_pl47' : 'Szanowny kliencie, jeśli masz aktywne zamówienia, Twoje dane osobowe zostaną usunięte w ciągu 48 godzin od momentu ich realizacji.',
    'l_pl48' : 'Odmowa przetwarzania danych osobowych',
    'l_pl49' : 'Złożyć zamówienie',
    'l_pl50' : 'Wpisz swoje imię',
    'l_pl51' : 'Wprowadź swój numer telefonu',
    'l_pl52' : 'Imię i nazwisko',
    'l_pl53' : 'Pole „Telefon” zostało wypełnione nieprawidłowo',
    'l_pl54' : 'Błąd połączenia, odśwież stronę',
    'l_pl55' : 'Wystąpił błąd',
    'l_pl56' : 'Upewnij się, że numer został wprowadzony poprawnie',
    'l_pl57' : 'stycznia',
    'l_pl58' : 'lutego',
    'l_pl59' : 'marca',
    'l_pl60' : 'kwietnia',
    'l_pl61' : 'maja',
    'l_pl62' : 'czerwca',
    'l_pl63' : 'lipca',
    'l_pl64' : 'sierpnia',
    'l_pl65' : 'września',
    'l_pl66' : 'października',
    'l_pl67' : 'listopada',
    'l_pl68' : 'grudnia',
    'l_pl69' : 'niedziela',
    'l_pl70' : 'poniedziałek',
    'l_pl71' : 'wtorek',
    'l_pl72' : 'środa',
    'l_pl73' : 'czwartek',
    'l_pl74' : 'piątek',
    'l_pl75' : 'sobota',
    'l_pl76' : 'Drogi Kliencie'
}
