window.l_loc =  {
    'l_pl1' : 'Sie haben das Feld "Telefonnummer" nicht ausgefüllt',
    'l_pl2' : 'Sie haben das Feld "Name, Vorname" nicht ausgefüllt',
    'l_pl3' : 'Das Feld "Name, Vorname" ist nicht korrekt ausgefüllt',
    'l_pl4' : 'Es wurde eine zu kurze Telefonnummer eingegeben',
    'l_pl5' : 'Es wurde eine zu lange Telefonnummer eingegeben',
    'l_pl6' : 'Leider ist bei der Bestellung ein Fehler unterlaufen. Bitte rufen Sie unter der Hotline 88003500589 an.',
    'l_pl7' : 'Sehr geehrter Kunde, Sie haben eine Kopie Ihrer Bestellung erstellt. Falls Sie eine Korrektur an der erstgetätigten Bestellung vornehmen möchten, warten Sie bitte den Anruf des Logistikleiters ab, dann können Sie alle nötigen Änderungen vornehmen lassen.',
    'l_pl8' : 'Leider ist eine Lieferung in Ihr Land nicht möglich',
    'l_pl9' : 'Vielen Dank für Ihre Bestellung! Unser Manager wird sich in Kürze mit Ihnen in Verbindung setzen.',
    'l_pl10' : 'Bitte bestätigen Sie, dass die eingegebene Nummer korrekt ist:',
    'l_pl11' : 'JA',
    'l_pl12' : 'NEIN',
    'l_pl13' : 'Achtung, Aktion!',
    'l_pl14' : 'Ganz persönlich für Sie und nur jetzt bieten wir einen unschlagbaren <strong>Rabatt an!</strong>',
    'l_pl15' : 'Ganz persönlich für Sie und nur jetzt bieten wir einen unschlagbaren <strong><span class="green-text">Rabatt an!</span></strong>',
    'l_pl16' : 'Bestellen Sie sofort und genießen Sie die Vorteile der Aktion.',
    'l_pl17' : 'Aktionsangebote',
    'l_pl18' : 'Personen schauen sich derzeit diese Seite an',
    'l_pl19' : 'Achtung! Es ist nur noch ein Aktionsangebot erhältlich.',
    'l_pl20' : 'Telefonnummer:',
    'l_pl21' : 'Beispiel:+494550123452',
    'l_pl22' : 'Aktueller Preis:',
    'l_pl23' : 'Aktueller <br/> Preis:',
    'l_pl24' : 'Jetzt bestellen und {{discount_price}} {{currency}}',
    'l_pl25' : 'EINEN MOMENT!',
    'l_pl26' : 'Bevor Sie gehen, möchten wir Ihnen ein GESCHENK machen!',
    'l_pl27' : 'Wir sind bereit, den Preis um {{unload_price}} {{currency}} zu senken!',
    'l_pl28' : 'Um sie zu erhalten - klicken Sie auf den Button "Bleiben" dieser Seite',
    'l_pl29' : 'Überdenken Sie unser Angebot, bevor Sie gehen!',
    'l_pl30' : 'Wir sind bereit, Ihnen das Produkt zu SEHR günstigen Konditionen anzubieten!',
    'l_pl31' : 'Um das Angebot zu prüfen-klicken Sie auf "Bleiben" auf dieser Seite',
    'l_pl32' : 'Einen Rückruf anfordern',
    'l_pl33' : 'Wir rufen Sie innerhalb 1 Minute zurück',
    'l_pl34' : 'Alle Anrufe sind <strong>kostenfrei!</strong>',
    'l_pl35' : '<strong>Achtung!</strong> Um den Rabatt zu erhalten, nennen Sie bitte unserem Manager den Rabatt-Code: <b style="margin-top: 15px;font-size: 20px;" class="prefix_value"></b>',
    'l_pl36' : 'Datenschutzrichtlinien',
    'l_pl37' : 'Nutzungsvereinbarung',
    'l_pl38' : 'Ich warte auf einen Anruf',
    'l_pl39' : 'Wollen Sie nicht warten?',
    'l_pl40' : 'Sind übrig',
    'l_pl41' : 'Aktionsangebote',
    'l_pl42' : 'Aktionsangebote',
    'l_pl43' : ' ',
    'l_pl44' : 'Ungültiges "E-Mail" -Feld',
    'l_pl45' : 'Telefonnummer',
    'l_pl46' : 'Ablehnen',
    'l_pl47' : 'Sehr geehrter Kunde, Sie haben aktive Aufträge, nach deren Erfüllung, werden ihre persönlichen Daten innerhalb von 48 Stunden gelöscht',
    'l_pl48' : 'Ablehnung der Bearbeitung von persönlichen Daten',
    'l_pl49' : 'Eine Bestellung aufgeben',
    'l_pl50' : 'Gib deinen Namen ein',
    'l_pl51' : 'Trage deine Telefonnummer ein',
    'l_pl52' : 'Vollständiger Name',
    'l_pl53' : 'Das Feld "Telefon" ist falsch ausgefüllt',
    'l_pl54' : 'Kommunikationsfehler, aktualisieren Sie die Seite',
    'l_pl55' : 'Fehler aufgetreten',
    'l_pl56' : 'Bestätigen Sie, dass die Nummer korrekt ist',
    'l_pl57' : 'Januar',
    'l_pl58' : 'Februar',
    'l_pl59' : 'März',
    'l_pl60' : 'April',
    'l_pl61' : 'Mai',
    'l_pl62' : 'Juni',
    'l_pl63' : 'Juli',
    'l_pl64' : 'August',
    'l_pl65' : 'September',
    'l_pl66' : 'Oktober',
    'l_pl67' : 'November',
    'l_pl68' : 'Dezember',
    'l_pl69' : 'sonntag',
    'l_pl70' : 'montag',
    'l_pl71' : 'dienstag',
    'l_pl72' : 'mittwoch',
    'l_pl73' : 'donnerstag',
    'l_pl74' : 'freitag',
    'l_pl75' : 'samstag',
    'l_pl76' : 'Sehr geehrter Kunde'
}
