window.l_loc =  {
    'l_pl1' : 'Il campo "Telefono" non è stato compilato',
    'l_pl2' : 'Il campo "Nome completo" non è stato compilato',
    'l_pl3' : 'Il campo "Nome completo" non è corretto',
    'l_pl4' : 'Il numero di telefono inserito è troppo breve',
    'l_pl5' : 'Il numero di telefono inserito è troppo lungo',
    'l_pl6' : 'Purtroppo si è verificato un errore durante la creazione dell\'ordine. Si prega di chiamare la nostra linea diretta al numero +48123456789',
    'l_pl7' : 'Gentile cliente, hai creato un ordine duplicato. Se è necessario apportare modifiche all\'ordine iniziale, attendere una chiamata dal responsabile della logistica e apportare le modifiche necessarie.',
    'l_pl8' : 'Siamo spiacenti, la consegna nel tuo Paese non è disponibile.',
    'l_pl9' : 'Grazie per il tuo ordine. Un nostro responsabile ti contatterà a breve!',
    'l_pl10' : 'Conferma se il numero inserito è corretto:',
    'l_pl11' : 'SI',
    'l_pl12' : 'NO',
    'l_pl13' : 'Attenzione, promozione!',
    'l_pl14' : 'Solo per te, e solo in questo momento ti offriamo uno straordinario <strong>sconto!</strong>',
    'l_pl15' : 'Solo per te, e solo in questo momento ti offriamo uno straordinario <strong><span class="green-text">sconto!</span></strong>',
    'l_pl16' : 'Effettua subito un ordine e usufruisci delle condizioni di questa promozione.',
    'l_pl17' : 'offerte promozionali',
    'l_pl18' : 'persone stanno visualizzando questa pagina',
    'l_pl19' : 'Attenzione! Questa è l\'ultima offerta promozionale.',
    'l_pl20' : 'Telefono:',
    'l_pl21' : 'Esempio: +394550123456',
    'l_pl22' : 'Prezzo corrente:',
    'l_pl23' : 'Prezzo <br/> corrente:',
    'l_pl24' : 'Ordina e risparmia {{discount_price}} {{currency}}',
    'l_pl25' : 'ASPETTA UN ATTIMO!',
    'l_pl26' : 'Prima di uscire, vogliamo offrirti un REGALO!',
    'l_pl27' : 'Possiamo ridurre il prezzo di {{unload_price}} {{currency}}!',
    'l_pl28' : 'Per ottenere lo sconto, clicca sul pulsante "Rimani" in questa pagina',
    'l_pl29' : 'Prima di uscire, considera la nostra offerta!',
    'l_pl30' : 'Possiamo fornirti prodotti in OTTIME condizioni!',
    'l_pl31' : 'Per considerare l\'offerta, clicca sul pulsante "Rimani" in questa pagina.',
    'l_pl32' : 'Richiedi una chiamata',
    'l_pl33' : 'Ti richiameremo tra un minuto!',
    'l_pl34' : 'Tutte le chiamate sono <strong>gratuite!</strong>',
    'l_pl35' : '<strong>Attenzione!</strong> Per ricevere lo sconto, comunicare al responsabile il codice promozionale: <b style="margin-top: 15px;font-size: 20px;" class="prefix_value"></b>',
    'l_pl36' : 'Politica sulla privacy',
    'l_pl37' : 'Accordo per gli utenti',
    'l_pl38' : 'Aspetto una chiamata',
    'l_pl39' : 'Non vuoi aspettare?',
    'l_pl40' : 'Rimaste',
    'l_pl41' : 'offerte promozionali',
    'l_pl42' : 'offerte promozionali',
    'l_pl43' : ' ',
    'l_pl44' : 'Campo "E-mail" non valido',
    'l_pl45' : 'Numero di telefono',
    'l_pl46' : 'Da asporto',
    'l_pl47' : 'Gentile cliente, se Lei ha ordini attivi, i suoi dati personali verranno cancellati entro 48 ore dal momento della loro esecuzione.',
    'l_pl48' : 'Rifiuto al trattamento dei dati personali',
    'l_pl49' : 'Ordina',
    'l_pl50' : 'Inserisci il tuo nome',
    'l_pl51' : 'Inserisci il numero di telefono',
    'l_pl52' : 'Nome completo',
    'l_pl53' : 'Campo \'Telefono\' non valido',
    'l_pl54' : 'Errore di comunicazione. Aggiornare la pagina',
    'l_pl55' : 'Si è verificato un errore',
    'l_pl56' : 'Verificare che il numero sia corretto',
    'l_pl57' : 'gennaio',
    'l_pl58' : 'febbraio',
    'l_pl59' : 'marzo',
    'l_pl60' : 'aprile',
    'l_pl61' : 'maggio',
    'l_pl62' : 'giugno',
    'l_pl63' : 'luglio',
    'l_pl64' : 'agosto',
    'l_pl65' : 'settembre',
    'l_pl66' : 'ottobre',
    'l_pl67' : 'novembre',
    'l_pl68' : 'dicembre',
    'l_pl69' : 'domenica',
    'l_pl70' : 'lunedì',
    'l_pl71' : 'martedì',
    'l_pl72' : 'mercoledi',
    'l_pl73' : 'giovedì',
    'l_pl74' : 'venerdì',
    'l_pl75' : 'sabato',
    'l_pl76' : 'Gentile cliente',
    'l_pl77' : 'C\'è stato un errore. Riprova tra 24 ore.'
}
