window.l_loc =  {
    'l_pl1' : 'Nu ați completat câmpul "Telefon"',
    'l_pl2' : 'Nu ați completat câmpul "Nume Prenume"',
    'l_pl3' : 'Câmpul "Nume Prenume" nu este completat corect.',
    'l_pl4' : 'Numărul de telefon introdus este prea scurt',
    'l_pl5' : 'Numărul de telefon introdus este prea lung',
    'l_pl6' : 'Din păcate, a apărut o eroare în timpul creării comenzii, vă rugăm să sunați la linia telefonică 88003500589',
    'l_pl7' : 'Stimate client, ați creat o comandă dublă. Dacă doriţi să schimbați comanda inițială, vă rugăm așteptați apelul managerului de logistică și apoi veţi puteți schimba comanda.',
    'l_pl8' : 'Ne pare rău, nu se poate face livrarea în țara dvs. ',
    'l_pl9' : 'Vă mulțumim pentru comandă, în cel mai scurt timp, managerul nostru vă va contacta!',
    'l_pl10' : 'Confirmați că numărul introdus este corect:',
    'l_pl11' : 'DA',
    'l_pl12' : 'NU',
    'l_pl13' : 'Atenție, promoţie!',
    'l_pl14' : 'Numai pentru dvs., și doar în acest moment oferim un <strong>discount uimitor!</strong>',
    'l_pl15' : 'Numai pentru dvs., și doar în acest moment oferim un <strong><span class="green-text">discount uimitor!</span></strong>',
    'l_pl16' : 'Plasați o comandă chiar acum și beneficiaţi de această promoție.',
    'l_pl17' : 'oferte promoționale',
    'l_pl18' : 'persoane vizionează această pagină',
    'l_pl19' : 'Atenție! A mai rămas o singură ofertă promoțională.',
    'l_pl20' : 'Telefon:',
    'l_pl21' : 'Exemplu: +404550123456',
    'l_pl22' : 'Prețul actual:',
    'l_pl23' : 'Prețul <br/> actual:',
    'l_pl24' : 'Comandaţi și economisiţi {{discount_price}} {{currency}}',
    'l_pl25' : 'O SECUNDĂ!',
    'l_pl26' : 'Înainte de a părăsi pagina, vrem să vă oferim un CADOU!',
    'l_pl27' : 'Готови сме да намалим цената на {{unload_price}} {{currency}}!',
    'l_pl28' : 'Pentru a beneficia de promoție - faceți clic pe butonul "Rămân" pe această pagină',
    'l_pl29' : 'Înainte de a părăsi pagina, luaţi în considerare oferta noastră!',
    'l_pl30' : 'Suntem gata să vă oferim produsele la prețuri FOARTE bune!',
    'l_pl31' : 'Pentru a vedea oferta - faceți clic pe butonul "Rămân" pe această pagină',
    'l_pl32' : 'Solicitați să fiți apelat.',
    'l_pl33' : 'Vă vom apela într-un minut!',
    'l_pl34' : 'Toate apelurile sunt <strong>gratuite!</strong>',
    'l_pl35' : '<strong>Atenție! </strong> Pentru a obține reducerea, dictaţi codul ofertei managerului: <b style="margin-top: 15px;font-size: 20px;" class="prefix_value"></b>',
    'l_pl36' : 'Politica de confidențialitate',
    'l_pl37' : 'Acordul utilizatorului',
    'l_pl38' : 'Aștept apel',
    'l_pl39' : 'Nu doriţi să așteptaţi?',
    'l_pl40' : 'A mai rămas',
    'l_pl41' : 'oferte promoționale',
    'l_pl42' : 'oferte promoționale',
    'l_pl43' : 'Acum',
    'l_pl44' : 'Câmpul "e-mail"  nu este completat corect',
    'l_pl45' : 'Numărul de telefon',
    'l_pl46' : 'Takeout',
    'l_pl47' : 'Stimate client, dacă aveți comenzi active, datele dvs. personale vor fi șterse în 48 de ore de la momentul procesării lor.',
    'l_pl48' : 'Refuz de a procesa datele personale',
    'l_pl49' : 'Comandaţi',
    'l_pl50' : 'Introduceți numele',
    'l_pl51' : 'Introduceți numărul de telefon',
    'l_pl52' : 'Nume Prenume',
    'l_pl53' : 'Câmpul "Telefon"  nu este completat corect',
    'l_pl54' : 'Eroare de comunicare. Reîmprospătați pagina',
    'l_pl55' : 'A intervenit o eroare',
    'l_pl56' : 'Confirmați nr. de telefon ',
    'l_pl57' : 'ianuarie',
    'l_pl58' : 'februarie',
    'l_pl59' : 'martie',
    'l_pl60' : 'aprilie',
    'l_pl61' : 'mai',
    'l_pl62' : 'iunie',
    'l_pl63' : 'iulie',
    'l_pl64' : 'august',
    'l_pl65' : 'septembrie',
    'l_pl66' : 'octombrie',
    'l_pl67' : 'noiembrie',
    'l_pl68' : 'decembrie',
    'l_pl69' : 'duminică',
    'l_pl70' : 'luni',
    'l_pl71' : 'marți',
    'l_pl72' : 'miercuri',
    'l_pl73' : 'joi',
    'l_pl74' : 'vineri',
    'l_pl75' : 'sâmbătă',
    'l_pl76' : 'Stimate client',
    'l_pl77' : 'A avut loc o eroare. Încercați din nou în 24 de ore.'
}
