window.l_loc =  {
    'l_pl1' : 'La casilla del "Teléfono" está incompleta',
    'l_pl2' : 'No ha completado la casilla "Nombre completo"',
    'l_pl3' : 'La casilla del "Nombre completo" esta llenada de forma incorrecta',
    'l_pl4' : 'El número de teléfono introducido es demasiado corto',
    'l_pl5' : 'El número de teléfono introducido es demasiado largo',
    'l_pl6' : 'Desafortunadamente, se produjo un error al crear el pedido, llame a la línea directa 88003500589',
    'l_pl7' : 'Estimado cliente, usted ha creado un pedido duplicado. Si necesita realizar ajustes en el pedido inicial, por favor espere una llamada del encargado de logística y podrá hacer los ajustes necesarios.',
    'l_pl8' : 'Lo sentimos, no se realizan las entregas en su país',
    'l_pl9' : '¡Gracias por el pedido, muy pronto nuestro ejecutivo de ventas se pondrá en contacto con usted!',
    'l_pl10' : 'Confirme si el número indicado es correcto:',
    'l_pl11' : 'SI',
    'l_pl12' : 'NO',
    'l_pl13' : '¡Atención, promoción!',
    'l_pl14' : '¡Personalmente para usted, y solo en este momento le ofrecemos un descuento <strong>increíble!</strong>',
    'l_pl15' : '¡Personalmente para usted, y solo en este momento le ofrecemos un descuento <strong><span class="green-text">increíble!</span></strong>',
    'l_pl16' : 'Haga un pedido ahora mismo y utilice las condiciones de esta promoción.',
    'l_pl17' : 'ofertas promocionales',
    'l_pl18' : 'personas están viendo esta página en este momento',
    'l_pl19' : '¡Atención! Queda la última oferta promocional.',
    'l_pl20' : 'Teléfono:',
    'l_pl21' : 'Ejemplo: +34550123456',
    'l_pl22' : 'Precio actual:',
    'l_pl23' : 'Precio <br/> actual:',
    'l_pl24' : 'Ordena y ahorra {{discount_price}} {{currency}}',
    'l_pl25' : '¡UN SEGUNDO!',
    'l_pl26' : '¡Antes de que se vaya, queremos ofrecerle un REGALO!',
    'l_pl27' : '¡Estamos listos para rebajar el precio en {{unload_price}} {{currency}}!',
    'l_pl28' : 'Para obtenerlo, haga clic en el botón "Quedarse" en esta página',
    'l_pl29' : '¡Antes de salir, considera nuestra oferta!',
    'l_pl30' : '¡Estamos listos para ofrecerle productos con muy buenas condiciones!',
    'l_pl31' : 'Para considerar la oferta, haga clic en el botón "Permanecer" en esta página.',
    'l_pl32' : 'Solicitar devolución de llamada',
    'l_pl33' : '¡Le devolveremos la llamada en 1 minuto!',
    'l_pl34' : '¡Todas las llamadas son <strong>gratuitas!</strong>',
    'l_pl35' : '<strong>¡Atención! </strong> Para obtener un descuento, dicte el código de promoción al ejecutivo de ventas: <b style="margin-top: 15px;font-size: 20px;" class="prefix_value"></b>',
    'l_pl36' : 'Política de privacidad',
    'l_pl37' : 'Acuerdo de usuario',
    'l_pl38' : 'Estoy esperando una llamada',
    'l_pl39' : '¿No desea esperar?',
    'l_pl40' : 'Solo quedan',
    'l_pl41' : 'ofertas promocionales',
    'l_pl42' : 'ofertas promocionales',
    'l_pl43' : 'En este momento',
    'l_pl44' : 'Campo "E-mail" no válido',
    'l_pl45' : 'Numero de telefono',
    'l_pl46' : 'Rechazar',
    'l_pl47' : 'Estimado cliente, en caso de tener pedidos en curso, desde el momento en que estos se completen, sus datos personales será eliminados en un plazo de 48 horas ',
    'l_pl48' : 'Rechazo del procesamiento de datos personales',
    'l_pl49' : 'Ordena',
    'l_pl50' : 'Introduzca su nombre',
    'l_pl51' : 'Ingrese su número telefónico',
    'l_pl52' : 'Nombre completo',
    'l_pl53' : 'Campo “Teléfono” no es válido.',
    'l_pl54' : 'Error de comunicación, actualizar la página.',
    'l_pl55' : 'Se ha producido un error',
    'l_pl56' : 'Por favor, confirme que el número es correcto.',
    'l_pl57' : 'de enero',
    'l_pl58' : 'de febrero',
    'l_pl59' : 'de marzo',
    'l_pl60' : 'de abril',
    'l_pl61' : 'de mayo',
    'l_pl62' : 'de junio',
    'l_pl63' : 'de julio',
    'l_pl64' : 'de agosto',
    'l_pl65' : 'de septiembre',
    'l_pl66' : 'de octubre',
    'l_pl67' : 'de noviembre',
    'l_pl68' : 'de diciembre',
    'l_pl69' : 'domingo',
    'l_pl70' : 'lunes',
    'l_pl71' : 'martes',
    'l_pl72' : 'miércoles',
    'l_pl73' : 'jueves',
    'l_pl74' : 'viernes',
    'l_pl75' : 'sábado',
    'l_pl76' : 'Estimado cliente',
    'l_pl77' : 'Se ha producido un error. Vuelva a intentarlo en 24 horas.'
}
